asaasdev/postman-collection

- asaasPostmanCollection.json
Foi adicionado um grupo para o Pix contendo as seguintes requisições:
- [ GET ] Recuperação de uma única transação pix através de seu ID
- [ GET ] Listagem de todas as transações pix
- [ POST ] Cancelamento de uma transação pix ***agendada***
https://asaasdev.atlassian.net/browse/MOB-649
https://github.com/asaasdev/asaas/pull/17360 -> Busca individual
https://github.com/asaasdev/asaas/pull/17429 -> Listagem e cancelamento
https://github.com/asaasdev/asaas/pull/17566 -> Apiary
> Pix | Adicionado grupo para Pix

- .github/PULL_REQUEST_TEMPLATE.md
Cria template de descrição para os PR's
```markdown
```
> Adiciona template de descrição do PR

- asaasPostmanCollection.json
Adicionado endpoints para fazer as requisições de decode e pagamento do QRCode. Foi adicionado também a criação do QRCode estático, que já tinha sido liberado porém não constava nas collections.
https://asaasdev.atlassian.net/browse/MOB-650
https://github.com/asaasdev/asaas/pull/17604
> Pix | Endpoints para utilizar o decode e pagamento via QRCode

- asaasPostmanCollection.json
Já existe na documentação como realizar:
- Criação de uma chave Pix
- Listagem de todas as chaves Pix
- Recuperação de uma única chave Pix
- Remoção de uma chave Pix
porém ainda não existia essas requisições nos arquivos para requisição.
https://asaasdev.atlassian.net/browse/MOB-702
> Adicionando requisições para manipulação de chaves Pix

- asaasPostmanCollection.json
https://asaasdev.atlassian.net/jira/software/projects/MOB/boards/38?assignee=557058%3A306239d9-9eab-4a87-80c3-1b006158f2a4&selectedIssue=MOB-545
https://github.com/asaasdev/asaas/pull/17805
> Adicionado filtros de contas filhas

- asaasPostmanCollection.json
Adiciona os campos necessários para realizar um estorno parcial caso a forma de pagamento seja Pix.
https://asaasdev.atlassian.net/browse/MOB-672
https://github.com/asaasdev/asaas/pull/17838
> Adiciona atributos para realizar um estorno parcial

- asaasPostmanCollection.json
Criando as requests para criar Transfer via Pix (manual/chave), agendado ou não.
[Api Transfer](https://github.com/asaasdev/asaas/pull/17348)
> Atualizando API de transferências para o Pix

- asaasPostmanCollection.json
> Número de conta Asaas

- asaasPostmanCollection.json
Visa adicionar um novo endpoint na collection somente para recuperar a Wallet ID da conta.
https://github.com/asaasdev/asaas/pull/18431
> Recuperando wallet ID

- asaasPostmanCollection.json
Este PR visa atualizar a collection com base nesse PR de novos filtros da API [#18404](https://github.com/asaasdev/asaas/pull/18404)
Filtros adicionados:
estimatedCreditDate[ge]
estimatedCreditDate[le]
externalReference
> Adicionando filtros de data estimada de crédito e referenciador externo

- asaasPostmanCollection.json
Em algum momento foi removido uma vírgula do arquivo, o que causou erro no parse json do processo da action de deploy para a coleção no repositório do postman.
> Adicionando vírgula cujo ausência causava erro no parse json

- asaasPostmanCollection.json
1. Corrigindo corpo da requisição para Pix com chave
2. Adicionando pixAddressKeyType na request para criar Pix na API de transferências.
https://asaasdev.atlassian.net/browse/PIX2-301
https://github.com/asaasdev/asaas/pull/19650
> Corrigindo body para Pix com chave + Adicionando pixAddressKeyType

- asaasPostmanCollection.json
> Adicionando data de nascimento na criação da conta filha

- asaasPostmanCollection.json
Novo endpoint para atualização de notificações em lote
Antes para atualizar notificações via API , teria que ser feito uma a uma . Esse endpoint permite enviar uma lista de notificação para poder fazer as atualizações para um customer de uma vez.
https://asaasdev.atlassian.net/browse/MBT-126
https://github.com/asaasdev/asaas/pull/20123
> Novo endpoint de atualizar pagamento em lote

- README.md
Ajustando o README para padronizar o projeto público do Asaas.
> Atualizar README para padronizar com o do Insomnia

- asaasPostmanCollection.json
Adicionando rota da API de statistics de split que não havia sido adicionada ainda e também colocando filtros que serão inseridos após o PR
https://asaasdev.atlassian.net/jira/software/projects/STD/boards/143?selectedIssue=STD-36
[#21137](https://github.com/asaasdev/asaas/pull/21137)
> Adicionando rota de statistics de split e filtros

- asaasPostmanCollection.json
Adicionando a possibilidade de filtrar por usuários na API de Payments 
https://asaasdev.atlassian.net/jira/software/projects/STD/boards/143?selectedIssue=STD-32
[#21116](https://github.com/asaasdev/asaas/pull/21116)
> Adicionando filtro por usuario na API de Payments

- asaasPostmanCollection.json
Adicionando documentação de webhook de recarga de celular
URL 
`````
/api/v3/webhook/mobilePhoneRecharge
`````
Body
````json
{
"url": "https://www.exemplo.com/webhook/asaas",
"email": "marcelo.almeida@gmail.com",
"interrupted": false,
"enabled": true,
"apiVersion": 3,
"authToken": "5tLxsL6uoN"
}
````
- https://github.com/asaasdev/asaas/pull/23847
- https://asaasdev.atlassian.net/browse/MBT-95
> Adicionar requisição de configuração webhook de recarga de celular

- asaasPostmanCollection.json
Foi feito uma task adicionar rotas para download dos carnês de pagamento nas rotas privadas
Agora foi feito na documentação as rotas para download, para ficar acessível ao publico 
- https://asaasdev.atlassian.net/browse/MBT-437
- https://github.com/asaasdev/asaas/pull/24029
> novos endpoints

- asaasPostmanCollection.json
O valor usado nas rotas de cada request é feito via variável (domain) que o cliente configura.
> atualizando rota da api

- asaasPostmanCollection.json
Criando exemplo de requisição que usa o novo endpoint
[MBT-988](https://asaasdev.atlassian.net/browse/MBT-988)
- https://github.com/asaasdev/asaas/pull/31283
[MBT-988]: https://asaasdev.atlassian.net/browse/MBT-988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Novo endpoint: listar cobranças de parcelamento

- asaasPostmanCollection.json
Adicionando o endpoint de simular taxas.
https://asaasdev.atlassian.net/browse/ST-422
https://github.com/asaasdev/api-docs/pull/9
> Adicionando simulador de taxas

- README.md
Migramos a collection do Postman para uma que será atualizada automaticamente conforme o Open API Spec.
Após este PR ser mergeado, o repositório pode ser arquivado.
> Atualizar Readme sobre arquivamento do projeto
